language: php
php: [7.1, 7.2, nightly ]
sudo: false

env:

install:
- composer install --no-interaction --prefer-dist -o

script:
  - vendor/bin/phpunit

jobs:
  include:
    - stage: lint
      php: 7.1
      before_script:
        - composer create-project symplify/easy-coding-standard temp/ecs
      script:
        - temp/ecs/bin/ecs check src tests
        - vendor/bin/phpstan analyse src --level max --configuration phpstan.neon

    - stage: Coverage
      php: 7.1
      script:
        - vendor/bin/phpunit
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar;
        - php coveralls.phar --verbose;

  allow_failures:
    - php: nightly

cache:
  directories:
  - $HOME/.composer/cache/files

notifications:
  irc: "irc.freenode.org#phpdocumentor"
  slack:
    secure: "fjumM0h+4w3EYM4dpgqvpiCug7m4sSIC5+HATgwga/Nrc6IjlbWvGOv3JPgD3kQUhi18VmZfUYPmCv916SIbMnv8JWcrSaJXnPCgmxidvYkuzQDIw1HDJbVppGnkmwQA/qjIrM3sIEMfnu/arLRJQLI363aStZzGPxwIa4PDKcg="
  email:
  - me@mikevanriel.com
  - ashnazg@php.net
