language: php
php: [ 7.1, 7.2, nightly ]
sudo: false

env:

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - travis_retry composer install --no-interaction --prefer-dist --optimize-autoloader
  - travis_retry composer global require phpunit/phpunit # cannot use phpunit.phar or require-dev, because this package is a phpunit dep
  - travis_retry wget https://phar.io/releases/phive.phar

script:
  - /home/travis/.composer/vendor/bin/phpunit --no-coverage

jobs:
  include:
    - stage: coverage
      php: 7.1
      script:
        - /home/travis/.composer/vendor/bin/phpunit
      after_script:
        - travis_retry php phive.phar --no-progress install --trust-gpg-keys E82B2FB314E9906E php-coveralls/php-coveralls && ./tools/php-coveralls --verbose
        - travis_retry wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

    - stage: lint
      php: 7.1
      before_script:
        - travis_retry php phive.phar --no-progress install --trust-gpg-keys 8E730BA25823D8B5 phpstan
      script:
        - ./tools/phpstan analyse src --level max --configuration phpstan.neon
        - composer create-project symplify/easy-coding-standard temp/ecs && temp/ecs/bin/ecs check src tests

cache:
  directories:
  - $HOME/.composer/cache/files
  - $HOME/.phive

notifications:
  irc: "irc.freenode.org#phpdocumentor"
  slack:
    secure: "fjumM0h+4w3EYM4dpgqvpiCug7m4sSIC5+HATgwga/Nrc6IjlbWvGOv3JPgD3kQUhi18VmZfUYPmCv916SIbMnv8JWcrSaJXnPCgmxidvYkuzQDIw1HDJbVppGnkmwQA/qjIrM3sIEMfnu/arLRJQLI363aStZzGPxwIa4PDKcg="
  email:
  - me@mikevanriel.com
  - ashnazg@php.net
